name:                hask-gallery
version:             0.1.0.0
github:              "rodjjo/hask-gallery"
license:             BSD3
author:              "Rodrigo A. Araujo"
maintainer:          "rodjjo@gmail.com"
copyright:           "2020 Rodrigo Antonio de Araujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hask-gallery#readme>

dependencies:
- base >= 4.7 && < 5
- servant >= 0.16.2 && < 0.17.0
- servant-server >= 0.16.2 && < 0.18
- blaze-html >= 0.9.1.2 && < 0.10
- blaze-markup >= 0.8.2.4 && < 0.9
- aeson >= 1.4.7.1 && < 1.5
- directory >= 1.3.6.0 && < 1.4
- text >= 1.2.4.0 && < 1.3
- wai >= 3.2.2.1 && < 3.3
- warp >= 3.3.10 && < 3.4
- parseargs >= 0.2.0.9 && < 0.3
- filepath >= 1.4.2.1 && < 1.5
- bytestring >= 0.10.10.0 && < 1.0
- utf8-string >= 1.0.1.1 && < 2.0
- executable-path >= 0.0.3.1 && < 0.0.4
- regex-tdfa >= 1.3.0 && < 1.4
- process >= 1.6.8.0 && < 1.6.9
- split >= 0.2.3.4 && < 0.2.4
- time >= 1.8.0.0 && < 1.10
- zlib >= 0.6.0.0 && < 0.7
- stm >= 2.5.0.0 && < 2.6
- transformers >= 0.5.6.2  && < 2.6
- raw-strings-qq >= 1.1 && < 2.0
- file-embed >= 0.0.11.2 && < 0.0.12
- mime-types >= 0.1.0.9 && < 0.2
library:
  source-dirs: src

executables:
  hask-gallery-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-gallery

tests:
  hask-gallery-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hask-gallery
    - tasty >= 1.2.3 && < 1.3.0
    - tasty-smallcheck >= 0.8.0 && < 0.9
    - tasty-quickcheck >= 0.10.0.0 && < 0.11
    - tasty-hunit >= 0.10.0.0 && < 0.11
